#pragma once
#include <Windows.h>

typedef INT_PTR(CALLBACK *PROCFUNC)(HWND, WPARAM, LPARAM);

INT_PTR CALLBACK Unprocessed(HWND, WPARAM, LPARAM);

INT_PTR CALLBACK OnClose(HWND, WPARAM, LPARAM);
INT_PTR CALLBACK OnCreate(HWND, WPARAM, LPARAM);
INT_PTR CALLBACK OnDestroy(HWND, WPARAM, LPARAM);

INT_PTR CALLBACK OnCommand(HWND, WPARAM, LPARAM);
INT_PTR CALLBACK OnSelectChanged(HWND, WPARAM, LPARAM);

INT_PTR CALLBACK OnInput(HWND, WPARAM, LPARAM);
